version: "3"
services:
  web:
    container_name: foodOrderService
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/server
    environment:
      MYSQL_DATABASE: food_order
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: 0.0.0.0
      APPLICATION_SERVER_PORT: 3000
      APP_FORCE_SHUTDOWN_SECOND: 30

  # Database
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_order
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root